/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevinRouteImport } from './routes/devin'
import { Route as IndexRouteImport } from './routes/index'

const DevinRoute = DevinRouteImport.update({
  id: '/devin',
  path: '/devin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devin': typeof DevinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devin': typeof DevinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devin': typeof DevinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devin'
  id: '__root__' | '/' | '/devin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevinRoute: typeof DevinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devin': {
      id: '/devin'
      path: '/devin'
      fullPath: '/devin'
      preLoaderRoute: typeof DevinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevinRoute: DevinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
